#ifndef LICENSETOOL_GLOBAL_H
#define LICENSETOOL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LICENSETOOL_LIBRARY)
#  define LICENSETOOLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LICENSETOOLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LICENSETOOL_GLOBAL_H
