#ifndef BASECONTROLS_GLOBAL_H
#define BASECONTROLS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BASECONTROLS_LIBRARY)
#  define BASECONTROLSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BASECONTROLSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BASECONTROLS_GLOBAL_H
