#ifndef NETPROTOCOL_GLOBAL_H
#define NETPROTOCOL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NETPROTOCOL_LIBRARY)
#  define NETPROTOCOLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NETPROTOCOLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NETPROTOCOL_GLOBAL_H
