#ifndef AUTOTEST_GLOBAL_H
#define AUTOTEST_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AUTOTEST_LIBRARY)
#  define AUTOTESTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define AUTOTESTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AUTOTEST_GLOBAL_H
